### ISSUE TITLE
Support Debian packages with a three number version

### ISSUE THREAD

**Issue by Totktonada** [knazarov/mkrepo#16]
Tarantool Debian package files are named like `tarantool_2.2.1.47.gd50b9d6-1_amd64.deb`. [upstream_version](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-standards-version) component is `2.2.1.47.gd50b9d6` and consists of three numbers from a tag, one number from git describe and a git commit hash. We however have repositories with two number tags and so a package will be named like `tarantool-gis_0.1.22-1_amd64.deb`. In this case `debian_revision` component (named `dist` in mkrepo code) will be determined as 'all', while it is expected to be '1'. Not sure about consequenses, but it looks incorrect.

The problem appears due to this regexp (there is also `2.2.1.47` vs `2.2.1-47` problem, see #14, but I'm not about that here):

https://github.com/tarantool/mkrepo/blob/4153b321408032936a63f13beaa4ccb1d82bbe7a/debrepo.py#L248

To be honest I don't understood why we separate `revision` from a version here: it is not used anywhere and is not described in Debian policy as I see. Maybe we can simplify things and parse only `debian_revision` (`dist`) and [architecture](https://manpages.debian.org/buster/dpkg-dev/dpkg-name.1.en.html) from a package file name considering everything before as a package name and an upstream_version. I think we can lean on a last hyphen to do so (NB: verify that there are no architecture names that contain a hyphen). The [Debian policy](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-standards-version) specifies a version in the quite free form, so we should allow it to be in such form: `[A-Za-z0-9.+~-]+`.

We should also verify that things works well for RPM packages. I suggest to download all tarantool packagecloud repositories and check that all packages are parsed well. We can even create a unit test based on this. Maybe also worth to download a list of all package names in official Debian repositories and add them to the test.

@knazarov Are you have a vision on that?

**Comment by knazarov** [comment]
I agree that this needs testing and that we should also test on other public packages.

As for the version format -- I don't have any objections. Whatever works is probably fine.

**Comment by LeonidVas** [comment]
Now when the package name "tarantool-python_0.6.6-21_amd64.deb" has been parsed, the "dist" is "1".
